// <auto-generated />
using Demo_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo_1.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20220601141812_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Demo_1.CoronaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveCases")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Continent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCases")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTests")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CoronaModels");
                });
#pragma warning restore 612, 618
        }
    }
}
